### ISSUE TITLE
I am trying to withdraw an item, but getting error 503

### ISSUE THREAD

**Issue by EnelKyss** [dmarket/dm-trading-tools#9]
api url path : "/exchange/v1/withdraw-assets"
`
statusCode: 503, {"code":"Unavailable","message":"Service is temporary unavailable."}
`
I might be putting wrong ids... But if I did that, that wouldn't throw error 503, am I right ? So just to ensure...
the request body should be of this type: 
`{
  "assets": [
    {
      "classId": "string",
      "gameId": "string",
      "id": "string"
    }
  ],
  "requestId": "string"
}`
and I have filled it with 
`{
  "assets": [
    {
      "classId": "244572484:1336167975",
      "gameId": "tf2",
      "id": "7c38dbc5-61bc-5e5f-8289-f2b4741d623d"
    }
  ],
  "requestId": "135da4s65d4a"
}`

1. where do I get `requestId` (for now I just used some random characters)
2. is `id` the `itemId` obtained from item details by dmarket?
3. 
Lets skip to the code...
![image](https://user-images.githubusercontent.com/87972902/161307973-8010d9ed-50dc-4326-a2a2-aac371ee2736.png)

![image](https://user-images.githubusercontent.com/87972902/161308003-4b507d9f-3e55-46cb-8e30-987cd929f420.png)
![image](https://user-images.githubusercontent.com/87972902/161307892-c82f91b7-44b2-4a28-9d07-4ee58a83a8e5.png)
The headers should be good, they are working for example in case of using "/exchange/v1/offers-buy"
So where is the problem ? Am I just putting wrong ids, or the api endpoint is closed ?

**Comment by bigbadmytyx** [comment]
@EnelKyss Have you managed to withdraw assets with this endpoint?
